language: bash
services:
  - elasticsearch
before_install:
  - npm config set spin false
install:
  - npm install
  - bundle install --jobs=3 --retry=3 --deployment
script:
  - bash tasks/pre-commit
  - bash tasks/tests
  - rake sitemap:generate
sudo: false
notifications:
  email: false
